import type { Phone } from './types';

export const phones: Phone[] = [
  {
    id: 'apple-iphone-15-pro',
    name: 'iPhone 15 Pro',
    brand: 'Apple',
    price: 999,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro.jpg',
    specs: {
      display: '6.1" Super Retina XDR',
      camera: '48MP Main',
      battery: '3274 mAh',
      processor: 'A17 Pro',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'samsung-galaxy-s24-ultra',
    name: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    price: 1299,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra-5g-sm-s928-stylus.jpg',
    specs: {
      display: '6.8" Dynamic AMOLED 2X',
      camera: '200MP Wide',
      battery: '5000 mAh',
      processor: 'Snapdragon 8 Gen 3 for Galaxy',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'google-pixel-8-pro',
    name: 'Pixel 8 Pro',
    brand: 'Google',
    price: 999,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8-pro.jpg',
    specs: {
      display: '6.7" Super Actua LTPO OLED',
      camera: '50MP Octa PD Wide',
      battery: '5050 mAh',
      processor: 'Google Tensor G3',
      storage: '128GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'oneplus-12',
    name: 'OnePlus 12',
    brand: 'OnePlus',
    price: 799,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg',
    specs: {
      display: '6.82" ProXDR AMOLED',
      camera: '50MP Sony LYT-808',
      battery: '5400 mAh',
      processor: 'Snapdragon 8 Gen 3',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'apple-iphone-15',
    name: 'iPhone 15',
    brand: 'Apple',
    price: 799,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg',
    specs: {
      display: '6.1" Super Retina XDR',
      camera: '48MP Main',
      battery: '3349 mAh',
      processor: 'A16 Bionic',
      storage: '128GB',
      ram: '6GB',
      is5G: true,
    },
  },
  {
    id: 'samsung-galaxy-s24',
    name: 'Galaxy S24',
    brand: 'Samsung',
    price: 799,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-5g-sm-s921.jpg',
    specs: {
      display: '6.2" Dynamic AMOLED 2X',
      camera: '50MP Wide',
      battery: '4000 mAh',
      processor: 'Snapdragon 8 Gen 3 for Galaxy',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'google-pixel-8',
    name: 'Pixel 8',
    brand: 'Google',
    price: 699,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8.jpg',
    specs: {
      display: '6.2" Actua OLED',
      camera: '50MP Octa PD Wide',
      battery: '4575 mAh',
      processor: 'Google Tensor G3',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'nothing-phone-2',
    name: 'Nothing Phone (2)',
    brand: 'Nothing',
    price: 599,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/nothing-phone2.jpg',
    specs: {
      display: '6.7" LTPO OLED',
      camera: '50MP Main',
      battery: '4700 mAh',
      processor: 'Snapdragon 8+ Gen 1',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'samsung-galaxy-a55',
    name: 'Galaxy A55',
    brand: 'Samsung',
    price: 450,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55.jpg',
    specs: {
      display: '6.6" Super AMOLED',
      camera: '50MP Wide',
      battery: '5000 mAh',
      processor: 'Exynos 1480',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'google-pixel-7a',
    name: 'Pixel 7a',
    brand: 'Google',
    price: 499,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7a.jpg',
    specs: {
      display: '6.1" OLED',
      camera: '64MP Quad PD Quad Bayer Wide',
      battery: '4385 mAh',
      processor: 'Google Tensor G2',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'apple-iphone-se',
    name: 'iPhone SE (2022)',
    brand: 'Apple',
    price: 429,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-se-2022.jpg',
    specs: {
      display: '4.7" Retina HD',
      camera: '12MP Wide',
      battery: '2018 mAh',
      processor: 'A15 Bionic',
      storage: '64GB',
      ram: '4GB',
      is5G: true,
    },
  },
  {
    id: 'xiaomi-13t-pro',
    name: 'Xiaomi 13T Pro',
    brand: 'Xiaomi',
    price: 650,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-13t-pro.jpg',
    specs: {
      display: '6.67" CrystalRes AMOLED',
      camera: '50MP Main (Leica)',
      battery: '5000 mAh',
      processor: 'MediaTek Dimensity 9200+',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'realme-gt-2-pro',
    name: 'Realme GT 2 Pro',
    brand: 'Realme',
    price: 749,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/realme-gt2-pro.jpg',
    specs: {
      display: '6.7" 2K Super Reality LTPO 2.0',
      camera: '50MP Sony IMX766 OIS',
      battery: '5000 mAh',
      processor: 'Snapdragon 8 Gen 1',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'realme-12-pro-plus',
    name: 'Realme 12 Pro+',
    brand: 'Realme',
    price: 499,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/realme-12-pro-plus.jpg',
    specs: {
      display: '6.7" Curved Vision OLED',
      camera: '64MP Periscope Portrait',
      battery: '5000 mAh',
      processor: 'Snapdragon 7s Gen 2',
      storage: '256GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'realme-c67',
    name: 'Realme C67',
    brand: 'Realme',
    price: 229,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/realme-c67-4g.jpg',
    specs: {
      display: '6.72" FHD+',
      camera: '108MP 3X In-sensor Zoom',
      battery: '5000 mAh',
      processor: 'Snapdragon 685',
      storage: '128GB',
      ram: '8GB',
      is5G: false,
    },
  },
  {
    id: 'sony-xperia-1-v',
    name: 'Sony Xperia 1 V',
    brand: 'Sony',
    price: 1399,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-v.jpg',
    specs: {
      display: '6.5" 4K HDR OLED',
      camera: '48MP Exmor T for mobile',
      battery: '5000 mAh',
      processor: 'Snapdragon 8 Gen 2',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'asus-rog-phone-8-pro',
    name: 'Asus ROG Phone 8 Pro',
    brand: 'Asus',
    price: 1199,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-8-pro.jpg',
    specs: {
      display: '6.78" Samsung AMOLED',
      camera: '50MP IMX890',
      battery: '5500 mAh',
      processor: 'Snapdragon 8 Gen 3',
      storage: '512GB',
      ram: '16GB',
      is5G: true,
    },
  },
  {
    id: 'xiaomi-14-ultra',
    name: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    price: 1499,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-ultra.jpg',
    specs: {
        display: '6.73" WQHD+ Dynamic AMOLED',
        camera: '50MP Main (Leica)',
        battery: '5000 mAh',
        processor: 'Snapdragon 8 Gen 3',
        storage: '512GB',
        ram: '16GB',
        is5G: true,
    },
  },
  {
    id: 'honor-magic6-pro',
    name: 'Honor Magic6 Pro',
    brand: 'Honor',
    price: 1299,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/honor-magic6-pro.jpg',
    specs: {
      display: '6.8" LTPO OLED',
      camera: '50MP Wide',
      battery: '5600 mAh',
      processor: 'Snapdragon 8 Gen 3',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'huawei-pura-70-ultra',
    name: 'Huawei Pura 70 Ultra',
    brand: 'Huawei',
    price: 1450,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/huawei-pura-70-ultra.jpg',
    specs: {
      display: '6.8" LTPO OLED',
      camera: '50MP Retractable',
      battery: '5200 mAh',
      processor: 'Kirin 9010',
      storage: '512GB',
      ram: '16GB',
      is5G: true,
    },
  },
  {
    id: 'oppo-find-x7-ultra',
    name: 'Oppo Find X7 Ultra',
    brand: 'Oppo',
    price: 950,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-find-x7-ultra.jpg',
    specs: {
      display: '6.82" LTPO AMOLED',
      camera: '50MP Quad (Hasselblad)',
      battery: '5000 mAh',
      processor: 'Snapdragon 8 Gen 3',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'vivo-x100-pro',
    name: 'Vivo X100 Pro',
    brand: 'Vivo',
    price: 1100,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-x100-pro.jpg',
    specs: {
      display: '6.78" LTPO AMOLED',
      camera: '50MP Triple (Zeiss)',
      battery: '5400 mAh',
      processor: 'MediaTek Dimensity 9300',
      storage: '256GB',
      ram: '16GB',
      is5G: true,
    },
  },
  {
    id: 'realme-gt-6',
    name: 'Realme GT 6',
    brand: 'Realme',
    price: 600,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/realme-gt-6.jpg',
    specs: {
      display: '6.78" LTPO AMOLED',
      camera: '50MP Main',
      battery: '5500 mAh',
      processor: 'Snapdragon 8s Gen 3',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'realme-gt-neo-6',
    name: 'Realme GT Neo 6',
    brand: 'Realme',
    price: 450,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/realme-gt-neo6.jpg',
    specs: {
      display: '6.78" LTPO AMOLED',
      camera: '50MP Main',
      battery: '5500 mAh',
      processor: 'Snapdragon 8s Gen 3',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'realme-p1-pro',
    name: 'Realme P1 Pro',
    brand: 'Realme',
    price: 260,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/realme-p1-pro-5g.jpg',
    specs: {
      display: '6.7" AMOLED',
      camera: '50MP Main',
      battery: '5000 mAh',
      processor: 'Snapdragon 6 Gen 1',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'motorola-edge-50-ultra',
    name: 'Motorola Edge 50 Ultra',
    brand: 'Motorola',
    price: 1000,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-ultra.jpg',
    specs: {
      display: '6.7" P-OLED',
      camera: '50MP Main',
      battery: '4500 mAh',
      processor: 'Snapdragon 8s Gen 3',
      storage: '512GB',
      ram: '16GB',
      is5G: true,
    },
  },
  {
    id: 'sony-xperia-1-vi',
    name: 'Sony Xperia 1 VI',
    brand: 'Sony',
    price: 1399,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-vi.jpg',
    specs: {
      display: '6.5" LTPO OLED',
      camera: '48MP Wide',
      battery: '5000 mAh',
      processor: 'Snapdragon 8 Gen 3',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'asus-zenfone-11-ultra',
    name: 'Asus Zenfone 11 Ultra',
    brand: 'Asus',
    price: 899,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/asus-zenfone-11-ultra.jpg',
    specs: {
      display: '6.78" LTPO AMOLED',
      camera: '50MP Main',
      battery: '5500 mAh',
      processor: 'Snapdragon 8 Gen 3',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'motorola-moto-g-stylus-2024',
    name: 'Moto G Stylus (2024)',
    brand: 'Motorola',
    price: 399,
    image: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g-stylus-5g-2024.jpg',
    specs: {
      display: '6.7" P-OLED',
      camera: '50MP Main',
      battery: '5000 mAh',
      processor: 'Snapdragon 6 Gen 1',
      storage: '256GB',
      ram: '8GB',
      is5G: true,
    },
  }
];

export const brands = [...new Set(phones.map(p => p.brand))];
export const maxPrice = Math.max(...phones.map(p => p.price));
