import type { Phone } from './types';

export const phones: Phone[] = [
  {
    id: 'apple-iphone-15-pro',
    name: 'iPhone 15 Pro',
    brand: 'Apple',
    price: 999,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch-naturaltitanium?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1692845702708',
    specs: {
      display: '6.1" Super Retina XDR',
      camera: '48MP Main',
      battery: '3274 mAh',
      processor: 'A17 Pro',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'samsung-galaxy-s24-ultra',
    name: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    price: 1299,
    image: 'https://image-us.samsung.com/us/smartphones/galaxy-s24-ultra/images/galaxy-s24-ultra-highlights-kv-Titanium-Gray-mo.jpg?imbypass=true',
    specs: {
      display: '6.8" Dynamic AMOLED 2X',
      camera: '200MP Wide',
      battery: '5000 mAh',
      processor: 'Snapdragon 8 Gen 3 for Galaxy',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'google-pixel-8-pro',
    name: 'Pixel 8 Pro',
    brand: 'Google',
    price: 999,
    image: 'https://storage.googleapis.com/gweb-uniblog-publish-prod/images/pixel_8_pro_watch_2_porcelain_2_1.width-1300.height-731.format-webp.webp',
    specs: {
      display: '6.7" Super Actua LTPO OLED',
      camera: '50MP Octa PD Wide',
      battery: '5050 mAh',
      processor: 'Google Tensor G3',
      storage: '128GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'oneplus-12',
    name: 'OnePlus 12',
    brand: 'OnePlus',
    price: 799,
    image: 'https://oasis.op-mobile.opera.com/op12/02-5a5f78/02-5a5f78-360.png',
    specs: {
      display: '6.82" ProXDR AMOLED',
      camera: '50MP Sony LYT-808',
      battery: '5400 mAh',
      processor: 'Snapdragon 8 Gen 3',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'apple-iphone-15',
    name: 'iPhone 15',
    brand: 'Apple',
    price: 799,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch-blue?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1692923777975',
    specs: {
      display: '6.1" Super Retina XDR',
      camera: '48MP Main',
      battery: '3349 mAh',
      processor: 'A16 Bionic',
      storage: '128GB',
      ram: '6GB',
      is5G: true,
    },
  },
  {
    id: 'samsung-galaxy-s24',
    name: 'Galaxy S24',
    brand: 'Samsung',
    price: 799,
    image: 'https://images.samsung.com/is/image/samsung/p6pim/es/2401/gallery/es-galaxy-s24-sm-s921bzygeub-539572093?$650_519_PNG$',
    specs: {
      display: '6.2" Dynamic AMOLED 2X',
      camera: '50MP Wide',
      battery: '4000 mAh',
      processor: 'Snapdragon 8 Gen 3 for Galaxy',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'google-pixel-8',
    name: 'Pixel 8',
    brand: 'Google',
    price: 699,
    image: 'https://storage.googleapis.com/gweb-uniblog-publish-prod/images/H_Pixel_8_Hazel_Horizontal.width-1300.height-731.format-webp.webp',
    specs: {
      display: '6.2" Actua OLED',
      camera: '50MP Octa PD Wide',
      battery: '4575 mAh',
      processor: 'Google Tensor G3',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'nothing-phone-2',
    name: 'Nothing Phone (2)',
    brand: 'Nothing',
    price: 599,
    image: 'https://cdn.shopify.com/s/files/1/0663/8213/1168/files/Phone_2__1_2048x.png?v=1691992087',
    specs: {
      display: '6.7" LTPO OLED',
      camera: '50MP Main',
      battery: '4700 mAh',
      processor: 'Snapdragon 8+ Gen 1',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'samsung-galaxy-a55',
    name: 'Galaxy A55',
    brand: 'Samsung',
    price: 450,
    image: 'https://images.samsung.com/is/image/samsung/p6pim/es/2403/gallery/es-galaxy-a55-5g-sm-a556bzkgeub-539828322?$650_519_PNG$',
    specs: {
      display: '6.6" Super AMOLED',
      camera: '50MP Wide',
      battery: '5000 mAh',
      processor: 'Exynos 1480',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'google-pixel-7a',
    name: 'Pixel 7a',
    brand: 'Google',
    price: 499,
    image: 'https://m.media-amazon.com/images/I/71m6kCB99FL._AC_UF894,1000_QL80_.jpg',
    specs: {
      display: '6.1" OLED',
      camera: '64MP Quad PD Quad Bayer Wide',
      battery: '4385 mAh',
      processor: 'Google Tensor G2',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'apple-iphone-se',
    name: 'iPhone SE (2022)',
    brand: 'Apple',
    price: 429,
    image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-se-finish-select-202207-starlight?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1655312338138',
    specs: {
      display: '4.7" Retina HD',
      camera: '12MP Wide',
      battery: '2018 mAh',
      processor: 'A15 Bionic',
      storage: '64GB',
      ram: '4GB',
      is5G: true,
    },
  },
  {
    id: 'xiaomi-13t-pro',
    name: 'Xiaomi 13T Pro',
    brand: 'Xiaomi',
    price: 650,
    image: 'https://i01.appmifile.com/v1/BIG/N_4_4/M_BIG_13T-Pro_13T-Pro-Alpine-Blue_1695710606.png',
    specs: {
      display: '6.67" CrystalRes AMOLED',
      camera: '50MP Main (Leica)',
      battery: '5000 mAh',
      processor: 'MediaTek Dimensity 9200+',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'realme-gt-2-pro',
    name: 'Realme GT 2 Pro',
    brand: 'Realme',
    price: 749,
    image: 'https://image.realme.com/eu/global/gt2-pro/m-img-2-1.png',
    specs: {
      display: '6.7" 2K Super Reality LTPO 2.0',
      camera: '50MP Sony IMX766 OIS',
      battery: '5000 mAh',
      processor: 'Snapdragon 8 Gen 1',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'realme-12-pro-plus',
    name: 'Realme 12 Pro+',
    brand: 'Realme',
    price: 499,
    image: 'https://image.realme.com/eu/global/12-pro-plus-5g/img-pc-3-2.png',
    specs: {
      display: '6.7" Curved Vision OLED',
      camera: '64MP Periscope Portrait',
      battery: '5000 mAh',
      processor: 'Snapdragon 7s Gen 2',
      storage: '256GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'realme-c67',
    name: 'Realme C67',
    brand: 'Realme',
    price: 229,
    image: 'https://image.realme.com/content/dam/realme/global/c67/sunny-oasis.png',
    specs: {
      display: '6.72" FHD+',
      camera: '108MP 3X In-sensor Zoom',
      battery: '5000 mAh',
      processor: 'Snapdragon 685',
      storage: '128GB',
      ram: '8GB',
      is5G: false,
    },
  },
  {
    id: 'sony-xperia-1-v',
    name: 'Sony Xperia 1 V',
    brand: 'Sony',
    price: 1399,
    image: 'https://www.sony.es/image/5d02da96015b940989345e8354c03387?fmt=pjpeg&wid=1400&resMode=bisharp',
    specs: {
      display: '6.5" 4K HDR OLED',
      camera: '48MP Exmor T for mobile',
      battery: '5000 mAh',
      processor: 'Snapdragon 8 Gen 2',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'asus-rog-phone-8-pro',
    name: 'Asus ROG Phone 8 Pro',
    brand: 'Asus',
    price: 1199,
    image: 'https://dlcdnwebimgs.asus.com/gain/3D7A6154-A60A-4074-927A-459E4E42D5F0/w750/h470',
    specs: {
      display: '6.78" Samsung AMOLED',
      camera: '50MP IMX890',
      battery: '5500 mAh',
      processor: 'Snapdragon 8 Gen 3',
      storage: '512GB',
      ram: '16GB',
      is5G: true,
    },
  },
  {
    id: 'xiaomi-14-ultra',
    name: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    price: 1499,
    image: 'https://i02.appmifile.com/i/S/S-Homepage-14-Ultra-Intro.png',
    specs: {
        display: '6.73" WQHD+ Dynamic AMOLED',
        camera: '50MP Main (Leica)',
        battery: '5000 mAh',
        processor: 'Snapdragon 8 Gen 3',
        storage: '512GB',
        ram: '16GB',
        is5G: true,
    },
  }
];

export const brands = [...new Set(phones.map(p => p.brand))];
export const maxPrice = Math.max(...phones.map(p => p.price));
