import type { Phone } from './types';

export const phones: Phone[] = [
  {
    id: 'apple-iphone-15-pro',
    name: 'iPhone 15 Pro',
    brand: 'Apple',
    price: 999,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '6.1" Super Retina XDR',
      camera: '48MP Main',
      battery: '3274 mAh',
      processor: 'A17 Pro',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'samsung-galaxy-s24-ultra',
    name: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    price: 1299,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '6.8" Dynamic AMOLED 2X',
      camera: '200MP Wide',
      battery: '5000 mAh',
      processor: 'Snapdragon 8 Gen 3 for Galaxy',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'google-pixel-8-pro',
    name: 'Pixel 8 Pro',
    brand: 'Google',
    price: 999,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '6.7" Super Actua LTPO OLED',
      camera: '50MP Octa PD Wide',
      battery: '5050 mAh',
      processor: 'Google Tensor G3',
      storage: '128GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'oneplus-12',
    name: 'OnePlus 12',
    brand: 'OnePlus',
    price: 799,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '6.82" ProXDR AMOLED',
      camera: '50MP Sony LYT-808',
      battery: '5400 mAh',
      processor: 'Snapdragon 8 Gen 3',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  },
  {
    id: 'apple-iphone-15',
    name: 'iPhone 15',
    brand: 'Apple',
    price: 799,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '6.1" Super Retina XDR',
      camera: '48MP Main',
      battery: '3349 mAh',
      processor: 'A16 Bionic',
      storage: '128GB',
      ram: '6GB',
      is5G: true,
    },
  },
  {
    id: 'samsung-galaxy-s24',
    name: 'Galaxy S24',
    brand: 'Samsung',
    price: 799,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '6.2" Dynamic AMOLED 2X',
      camera: '50MP Wide',
      battery: '4000 mAh',
      processor: 'Snapdragon 8 Gen 3 for Galaxy',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'google-pixel-8',
    name: 'Pixel 8',
    brand: 'Google',
    price: 699,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '6.2" Actua OLED',
      camera: '50MP Octa PD Wide',
      battery: '4575 mAh',
      processor: 'Google Tensor G3',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'nothing-phone-2',
    name: 'Phone (2)',
    brand: 'Nothing',
    price: 599,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '6.7" LTPO OLED',
      camera: '50MP Main',
      battery: '4700 mAh',
      processor: 'Snapdragon 8+ Gen 1',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
    {
    id: 'samsung-galaxy-a55',
    name: 'Galaxy A55',
    brand: 'Samsung',
    price: 450,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '6.6" Super AMOLED',
      camera: '50MP Wide',
      battery: '5000 mAh',
      processor: 'Exynos 1480',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'google-pixel-7a',
    name: 'Pixel 7a',
    brand: 'Google',
    price: 499,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '6.1" OLED',
      camera: '64MP Quad PD Quad Bayer Wide',
      battery: '4385 mAh',
      processor: 'Google Tensor G2',
      storage: '128GB',
      ram: '8GB',
      is5G: true,
    },
  },
  {
    id: 'apple-iphone-se',
    name: 'iPhone SE (2022)',
    brand: 'Apple',
    price: 429,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '4.7" Retina HD',
      camera: '12MP Wide',
      battery: '2018 mAh',
      processor: 'A15 Bionic',
      storage: '64GB',
      ram: '4GB',
      is5G: true,
    },
  },
  {
    id: 'xiaomi-13t-pro',
    name: 'Xiaomi 13T Pro',
    brand: 'Xiaomi',
    price: 650,
    image: 'https://placehold.co/400x600.png',
    specs: {
      display: '6.67" CrystalRes AMOLED',
      camera: '50MP Main (Leica)',
      battery: '5000 mAh',
      processor: 'MediaTek Dimensity 9200+',
      storage: '256GB',
      ram: '12GB',
      is5G: true,
    },
  }
];

export const brands = [...new Set(phones.map(p => p.brand))];
export const maxPrice = Math.max(...phones.map(p => p.price));
